require "rails_helper"

RSpec.describe "Authentication", type: :request do
  let(:headers) do
    {
      "Accept" => "application/json",
      "X-Company-Id" => @company.id.to_s
    }
  end

  describe "POST /signup" do
    # Build a user in memory using FactoryBot to get valid Faker data
    let(:user_attributes) { attributes_for(:user) }

    it "creates a new user" do
      post "/signup", params: user_attributes, headers: headers

      if response.status != 201
        puts "FAILED RESPONSE: #{response.status} - #{response.body}"
      end

      expect(response).to have_http_status(:created)

      # Check the tenant schema for the email generated by Faker
      Apartment::Tenant.switch('test') do
        expect(User.exists?(email: user_attributes[:email])).to be true
      end
    end
  end

  describe "POST /login" do
    # Generating the credentials
    let(:password) { "password123" }

    # Create the user in the 'test' schema
    let!(:user) do
      Apartment::Tenant.switch('test') do
        create(:user, password: password)
      end
    end

    it "logs in successfully" do
      post "/login", params: {
        user: {
          email: user.email,
          password: password
        }
      }, headers: headers

      if response.status != 201
        puts "LOGIN FAILED: #{response.status} - #{response.body}"
      end

      expect(response).to have_http_status(:created)
    end
  end
end
